"""Add photo_id to menu_items

Revision ID: 2d69dfdcfec0
Revises: 30a4cba5ecf2
Create Date: 2025-07-31 14:07:52.110720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d69dfdcfec0'
down_revision: Union[str, Sequence[str], None] = '30a4cba5ecf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('photo_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_items', 'photo_id')
    # ### end Alembic commands ###
